version: "3.9"

services:
  tor:
    image: dperson/torproxy:latest
    container_name: bs_tor
    restart: unless-stopped
    ports:
      - "9050:9050"
    environment:
      - PUID=1000
      - PGID=1000
    command: -a 'tor' -P '9050'

  api:
    build: ./apps/api
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - minio
    restart: unless-stopped

  workers:
    build: ./apps/workers
    env_file: .env
    depends_on:
      - redis
      - postgres
      - minio
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./services/postgres/data:/var/lib/postgresql/data
      - ./infra/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./services/minio/data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped

  label-studio:
    image: heartexlabs/label-studio:latest
    environment:
      - LABEL_STUDIO_HOST=http://0.0.0.0
    ports:
      - "8081:8080"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./services/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
