services:
  # 🌐 Web Service
  - type: web
    name: my-system-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./migrate.sh && uvicorn apps.api.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-system-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: my-system-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

  # 🧵 Celery Worker
  - type: worker
    name: my-system-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A apps.workers.tasks worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-system-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: my-system-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        sync: true

  # ⏰ Celery Beat Scheduler
  - type: worker
    name: my-system-beat
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A apps.workers.tasks beat --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-system-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: my-system-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        sync: true

databases:
  - name: my-system-db
    plan: free

services:
  - type: redis
    name: my-system-redis
    plan: free
