services:
  - type: web
    name: api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: ./migrate.sh && uvicorn apps.api.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        value: ""
      - key: REDIS_URL
        value: ""
    healthCheck:
      path: /healthz
      port: 10000
      intervalSeconds: 10
      timeoutSeconds: 5

  - type: worker
    name: worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A apps.workers.tasks worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        value: ""
      - key: REDIS_URL
        value: ""

  - type: worker
    name: beat
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A apps.workers.tasks beat --loglevel=info
    envVars:
      - key: DATABASE_URL
        value: ""
      - key: REDIS_URL
        value: ""
