version: "3.9"
services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: geo_postgis
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: geo_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
